[meta]
name = "Presets and Sharing"
author = "skybaxrider"
category = "Utilities"

siteid = 149
version = "1.0.0"

[script]
imports = [ "Icons.as" ]
# UNIT_TEST             - runs unit tests
# DEV_MODE              - keeps UI open through recompilation
# VERBOSE_SERIALIZATION - output logging for debugging serialization issues
defines = [ "" ]
